apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: app:latest
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_HOST
              value: mypsql
  # imagePullSecrets:
    # - name: regcred  # if you have a private registry, provide image pull secret

---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
